### ISSUE TITLE
Balance pass on experiment durations and Biome 

### ISSUE THREAD

**Issue by SerinaTsukaya** [Standecco/ROKerbalism#12]
An overview of Science experiments based on Node, completion time and whether they're biome dependant.
Note, this is based on commit 5e03c99 From Standecco /ROKerbalism

Legend:
Situations
L: Landed
S: Splashed
FL: Flying Low
FH: Flying High
SL: Space Low
SH: Space High
(B) Biome for that area

+Starting node:
- Supersonic Flight Analysis 1 Hour, FL/FH
- Telemetry Analysis 5 Min, L(B)/S(B)/FL(B)/FH/SL/SH
- Biological sample: 30 Min, L/FH/SL/SH
- Pressure Scan: 10 Min, L(B)/FL(B)/FH/SL/SH
- Temprature Scan: 10 Min, L(B)/FL(B)/FH(B)/SL/SH
- Planetary Photography: 1 Min, SL(B)

+Early Science:
- Mass Spectrometry: 60~ Min, L(B)/FH(B)/SL(B)/SH
- Biological Sample 2: 60~ Min, SL/SH

+Satellite Era Science:
- Photography 2: 2~Years, SL (Naming convention change?)
- Cosmic Ray Science: 91 Days, L/FH/SL/SH
- Magnetic Scan: 30~ Days, L(B)/SL(B)/SH
- Micrometorite Detection: 91~Days, SL/SH
- Visible Imaging: 20~ Min, L(B)/FH(B)/SL(B)/SH

+Early Human Spaceflight Era Science:
- Infrared Radiometry: 1 Day, SL(B)/SH(B)
- Orbital Perturbation Experiment: 10 Years, SL/SH

+Interplanetary Era Science:
- Cosmic Ray Science 2: 91 Days, L/FH/SL/SH
- Infrared Radiometry 2: 7 Days SL(B)/SH(B)
- Imaging Spectrometry: 91 Days SL(B)/SH(B) (Breaks naming convention)
- Magnetic Scan 2: 30~ Days L(B)/SL(B)/SH
- Mass Spectometry 2: 14 Days, L(B)/FH(B)/SL(B)/SH
- Scoop Surface Material: N/A
- Visible imaging 2: 1 Hour, Landed/SL(B)/SH

+Lunar exploration Science era:
- Mass Spectrometry 3: 91 Days,  L(B)/FH(B)/SL(B)/SH
- RPWS:                    7 Days, L/SL/SH

+Surface Science:
- Photography 3: 10 Years, SL

+Deep Space Science Experiments: (Note, this node contains parts with multiple same type experiments, (Photography 1,2,3 Etc) and the next nodes continue this trend)
- Photography 4: 20 Years, SL
- Magnetic Scan 3: 91 Days, L(B)/SL(B)/SH
- Infrared Radiometry 3: 30 Days, SL(B)/SH(B)
- Image Spectometry 2: 91 Days, SL(B)/SH(B)
- RPWS 3 (missing number 2): 180~ Days, L/SL/SH
- Visible Imaging 3: 2 Hours, L/SL(B)/SH
- Mass Spectometry 4: 91 Days L(B)/FH(B)/SL(B)/SH

+Exploration Era Science 
- Image Spectometry 3: 91~Days SL(B)/SH(B)
Anomaly: Advanced Visible Imaging Device has no new science, but is lighter than the one in Deep space science experiments

+Sample Return Science
RPWS 3: 180~ Days, L/SL/SH
Anomaly: The Radio and Plasma Wave Science RPWS has duplicate entries for RPWS 3, this along with there being no RPWS 2 experiment.
Anomaly: Pressure Modulated Infrared Radiometer has no new science, and is worse than the corresponding one in Deep Space Science Experiments.

+Advanced Science experiments:
Anomaly: High resolution imaging device has no new science and is of the Visible imaging type, Maybe Turn it into a deep space telescope experiment?

No more science found in the science nodes after this.

**Comment by Standecco** [comment]
95% of the work should have already been done now, thanks again for the help!
