### ISSUE TITLE
All instances of WarpFixer need to be renamed to SolarPanelFixer in configs

### ISSUE THREAD

**Issue by Gordon-Dry** [Standecco/ROKerbalism#13]
To be compatible with new sstu-and-solar fixes from this commit (already 2 months ago):
https://github.com/Kerbalism/Kerbalism/commit/d04c2dd9458ee4988fd9cd38f0ac911315882e27

**Comment by Gordon-Dry** [comment]
At least:
GameData\KerbalismConfig\System\Misc.cfg line 9

**Comment by gotmachine** [comment]
All the the config changes :

Main patch in KerbalismConfig : 
https://github.com/Kerbalism/Kerbalism/blob/a21905901110900fe9fafa4b8da8c343e53a2700/GameData/KerbalismConfig/System/Misc.cfg#L9

Mod support patches. Those are currently in the core Kerbalism folder, but we are in the process of moving them to KerbalismConfig for next release.

Kopernicus : 
https://github.com/Kerbalism/Kerbalism/blob/sstu-and-solar/GameData/Kerbalism/Support/Kopernicus.cfg

SSTU :
https://github.com/Kerbalism/Kerbalism/blob/a21905901110900fe9fafa4b8da8c343e53a2700/GameData/Kerbalism/Support/SSTU.cfg#L411

Near future solar :
https://github.com/Kerbalism/Kerbalism/blob/sstu-and-solar/GameData/Kerbalism/Support/NearFuture.cfg#L146

**Comment by Standecco** [comment]
Fixed with #14 and 73cb4492eed9a78eb4a3b52a8322f2fb13852d10
