### ISSUE TITLE
Early Film/Bio Sample experiments unbalanced

### ISSUE THREAD

**Issue by nepphhh** [Standecco/ROKerbalism#15]
Bio experiments seem way too expensive (250 funds) for how little science they give. An early film camera is the same cost but is superior in nearly every way: 
1) Early film duration is 5 minutes, bio is 30.
2) Early film can be used in low flying, bio cannot.
3) Early film has two slots and is biome-dependant, so with the short experiment duration, you can complete two valuable low-space or flying-high experiments in two different biomes in a single launch, or at least get flying high and low space in the same launch with only one experiment. Bio has a single slot and is biome-independant.

In short, you can easily get 10 science points in a single launch with a single early film experiment, but with bio experiments I think I get like 3 points at max per mission, and I need two parts (500 funds! on a sounding rocket one tenth that cost!) to get both flying high and low space.

I propose:
a) making early film experiments last 10 minutes, as they're a little easy to complete right now (I don't think I've ever needed two launches to finish an experiment).
b) Give bio experiments two slots, so they can complete flying high and low space at the same time.
c) Reduce bio experiment part cost to 50f.

**Comment by Standecco** [comment]
fixed in https://github.com/Standecco/ROKerbalism/tree/experiments-fix
