### ISSUE TITLE
LOX to GOX converter is not working.

### ISSUE THREAD

**Issue by Vannadin** [Standecco/ROKerbalism#17]
popup window shows  LOX to GOX converter state is "running", but it doesn't in planner.
![screenshot23](https://user-images.githubusercontent.com/23308367/63920940-d16f5280-ca7c-11e9-8c7d-e06fcd30627d.png)

**Comment by Standecco** [comment]
Fixed on 36653f43cbceea17a3b0ca5ac753f9d9f0e05a56
