### ISSUE TITLE
Incorrect power draw on Gemini capsule

### ISSUE THREAD

**Issue by Capkirk123** [Standecco/ROKerbalism#19]
Realism overhaul sets an avionics power draw to all capsules, to simulate their internal systems and life support. Kerbalism also adds power draw for life support, resulting in power draw ~1 kW higher than real life for the Gemini/ACP (~2.2kW for Gemini IRL, vs ~3.3 ingame when kerbalism is installed), which limits the duration of missions, as the onboard fuel cells are unable to keep up with the power draw. Kerbalism should probably decrease the power draw of RO configured capsules to just avionics power draw, and add life support power draw separately.

**Comment by Standecco** [comment]
I'll probably start manually patching EC consumption in various capsules, since I don't see a way to automatically do it. What mod is the Gemini you're using from, FASA?

**Comment by Capkirk123** [comment]
Yes, FASA. And interestingly enough, I launched one, and despite the claimed power draw in the hangar, the avionics drew no power at all, only kerbalism.

**Comment by Standecco** [comment]
I'm testing with the RO advanced capsule, which has the exact same life support and consumption, but with the reduced patch it goes down to 1.4 in total
![image](https://user-images.githubusercontent.com/43384369/65492371-11292e80-deb1-11e9-8df4-b1de282a38e9.png)

**Comment by YuryRugayn** [comment]
Second this problem on Rider Nick Soviet Spacecraft mod. Soyuz will lose all power in ~48 hours at 400 km orbit

**Comment by Standecco** [comment]
should be fixed now
