### ISSUE TITLE
RN Skylab does not have treadmill, life support

### ISSUE THREAD

**Issue by Capkirk123** [Standecco/ROKerbalism#26]
Skylab from the RN Skylab mod does not have a treadmill or any scrubbers, while the SXT skylab does. The power draw for both skylabs is also incorrect due to passive life support power draw being added by both RO and Kerbalism, although I assume this is already being dealt with along with all other capsules.

**Comment by Standecco** [comment]
Could you check what is the part name? Not the in-game one, but the actual name of the part in the configs

**Comment by Capkirk123** [comment]
The part name is simply skylab

**Comment by Standecco** [comment]
should be working
