### ISSUE TITLE
Unable to compete mission: First science satellite

### ISSUE THREAD

**Issue by YuryRugayn** [Standecco/ROKerbalism#30]
RP1 Milestone Mission: First science satellite
Stated critical goals: 
Have power for 120 min
Transmite Cosmic Ray Science (Radiation detector onboard) - unable to reach, no transmission at ~300 min (battery life time)
Experiment stated: "90 days to complete"

**Comment by Standecco** [comment]
That is, unfortunately, a known issue: the only thing you can do, for the moment, is completing the contract through the alt+f12 cheat window

**Comment by Standecco** [comment]
Should be fixed with d13c99cbe5271577321ad8c6895bfe441db90d82; 
The contract should now detect the experiment at 0.1 science collected, after less than a day.
