### ISSUE TITLE
Drop out of warp for random satellite out of power message

### ISSUE THREAD

**Issue by Bornholio** [Standecco/ROKerbalism#37]
Drop out of warp for random satellite out of power message is hard to manage as you get more sats.  with just a small comms constellation I have to spam KCT button presses to get to the next warp to item.

![pic](https://media.discordapp.net/attachments/531994741378646016/678675136311984128/unknown.png)

I think these should default off.

**Comment by Standecco** [comment]
I _think_ you can change the default behavior in the game settings, I can't do anything (config wise) about it.
