### ISSUE TITLE
2 Errors at load with MM

### ISSUE THREAD

**Issue by Robbie75** [Standecco/ROKerbalism#39]
I am getting 2 errors recently stating that it's in regards to "KerbalismConfig/support/sxt.cfg" 

this is fairly recent so by the looks of things perhaps sxt changed and is messing something up?
Just thought I would bring it to your attention. Running RSS, RO, RP-1 on 1.8.1 with all the bells and whistles. Not exactly sure of when it started cause I usually start the load and walk away for a few for it to load up, but I would think in the last couple weeks anyways.

**Comment by Standecco** [comment]
Try to upload your KSP.log - I can't do much without it

**Comment by fluff-y** [comment]
Hi,
I'm getting the same error message.
Currently playing on ROKerbalism version 1.0, KSP 1.9.1, running with RSS, RO, RP-1 and bunch of other accompanying mods.
All my mods should be up-to-date, i made a fresh install last week.

However, i was able to find these warnings/errors connected to ROKerbalism in the Player.log:
> [WRN 17:51:33.206] Errors in patch prevents the creation of the cache
2 errors related to GameData/KerbalismConfig/Support/SXT.cfg

> [LOG 17:49:34.860] Applying update KerbalismConfig/Support/SXT/@PART[SXTDepolyRTGI,SXTDepolyRTGII]:NEEDS[ProfileRealismOverhaul,SXT]:FOR[RP-0-Kerbalism] to SXT/Parts/StationsBases/Electrical/RTG/part.cfg/PART[SXTDepolyRTGII]
> [ERR 17:49:34.860] Error - Cannot parse variable search when inserting new key capacity = #$../MODULE[ModuleGenerator]/OUTPUT_RESOURCE[ElectricCharge]/rate$
> [LOG 17:49:34.860] Applying update KerbalismConfig/Support/SXT/@PART[SXTDepolyRTGI,SXTDepolyRTGII]:NEEDS[ProfileRealismOverhaul,SXT]:FOR[RP-0-Kerbalism] to SXT/Parts/StationsBases/Electrical/RTG/partBasic.cfg/PART[SXTDepolyRTGI]
> [ERR 17:49:34.860] Error - Cannot parse variable search when inserting new key capacity = #$../MODULE[ModuleGenerator]/OUTPUT_RESOURCE[ElectricCharge]/rate$

[Player-copy-pt1.log](https://github.com/Standecco/ROKerbalism/files/5404194/Player-copy-pt1.log)
[Player-copy-pt2.log](https://github.com/Standecco/ROKerbalism/files/5404195/Player-copy-pt2.log)

**Comment by Standecco** [comment]
Hey @fluff-y, thanks for the report. Could you post upload your ModuleManager.ConfigCache here?

**Comment by fluff-y** [comment]
Unfortunately the two errors prevent Module Manager from creating a cache file.
With the errors commented out i get the following ModuleManager.ConfigCache

[ModuleManager.ConfigCache.txt](https://github.com/Standecco/ROKerbalism/files/5516933/ModuleManager.ConfigCache.txt)

**Comment by Standecco** [comment]
That is caused by NFE's decaying RTG patch. It is not needed since ROKerbalism has that feature on its own, and will be more accurate than the stock patch that NFE has anyway. Also, be sure to uninstall Dynamic Battery Storage if you have that installed; it is incompatible with Kerbalism, as it does the same thing.

**Comment by fluff-y** [comment]
Thank you, removing decaying RTG solve it for me, also for pointing out Dynamic Battery Storage. I had it installed as well.
