### ISSUE TITLE
Data Storage/Hard drive not functioning (no storage on any part)

### ISSUE THREAD

**Issue by GenocidalTeacup** [Standecco/ROKerbalism#45]
I am rather new to RO and Kerbalism and have thoroughly researched but have not found an answer. No matter which part I use for my science tests I can not get any data storage - the UI for Data Storage cannot be clicked, is always empty and no matter the probe core or science core (tested mobile processing lab, various probe cores and different manned command pods). 

To be clear I use RSS/RO but not RP-1, my full mod list has been attached. I have also attached my KSP.log

As I am new here please let me know if anything else is required or if this has already been answered. Thanks a lot in advance for your help!

[CKAN_Modlist_Export.txt](https://github.com/Standecco/ROKerbalism/files/4645279/CKAN_Modlist_Export.txt)

[KSP.log](https://github.com/Standecco/ROKerbalism/files/4645276/KSP.log)

**Comment by Standecco** [comment]
Hi @GenocidalTeacup, as you may have noticed, the science configs for RO w/o RP-1 weren't developed or tested much. The reasoning behind this was that 1. RO is _supposed_ to be played in sandbox and that 2. ROKerbalism's science configs are so interlinked with RP-1's experiments and structure that it would be impossible to support experiments both with and without RP-1.

That said, Hard drive configs fall in this grey area were you can technically support them even without RP-1, but there's very little request for it and not much purpose in general. If you want to test them, I've pushed some small (untested!) patch ordering changes in d1d744b; these should fix your issue and give everything a 2GB, 3 sample slot storage. It's not historical, but it should be enough. I'm still deciding if I want real parts to have their real storage capacity.

Just to be sure on how to do this: download the entire repo and replace (by deleting the old folders first, very important) your old Kerbalism and KerbalismConfig folders with the ones in the ROKerbalism/GameData folder you just downloaded.

**Comment by GenocidalTeacup** [comment]
Hi @Standecco. Firstly I just wanted to thank you very much for taking the time to respond and push a new patch for me! I understand that the science configs in Kerbalism RO were not developed for sandbox mode, it makes perfect sense. The way I enjoy KSP is sandbox mode so I have access to any parts but still include and track science, flags etc.

I have installed and done an initial couple tests with the build you pushed and so far all probe cores show 2.05GB and I am able to transmit and perform science! So far so good, I will keep testing to see if any related bugs show up. Thanks again!
