### ISSUE TITLE
Problems with the science 

### ISSUE THREAD

**Issue by Octonath** [Standecco/ROKerbalism#49]
Hello, I have a problems with science even if i place computer for storage it don't work (with all the requirement of RO via CKAN) it's the thermometer TRO-CH0 and avery time i want to save the experiment it say "not enough space in hard drive". Can you help me understand ?

![KSP](https://user-images.githubusercontent.com/47495624/84838060-bedcfe80-b039-11ea-8404-053330758985.png)
![KSP2](https://user-images.githubusercontent.com/47495624/84838067-c1d7ef00-b039-11ea-86d6-8634800cd9ab.png)

**Comment by Standecco** [comment]
I'm guessing you're playing without RP-1 installed?

**Comment by Octonath** [comment]
Yes, Without it because i dunno how to remove the kerbal construction time

**Comment by Standecco** [comment]
Well, you just uninstall the mod or disable it through its settings. Science isn't supported without RP-1, because it's the mod that adds experiments and science parts (along with all career things)

**Comment by pap1723** [comment]
This should be closed.
