### ISSUE TITLE
KSP with Kerbalism RO config stalls after update to RO v12.7.1

### ISSUE THREAD

**Issue by codebori** [Standecco/ROKerbalism#5]
After I updated to RO v12.7.1 I couldn't start KSP anymore. I reinstalled all mods 1 by 1 and the issue occurred again after I installed Kerbalism RO Config.
I attached the following logs:
ROv12.7.0_Player.log: before update, no issues
OK.Player.log: clean install with ROv12.7.0, without kerbalism, no issues
Kerbalism.stall.Player.log: KSP stalls after installing kerbalism RO Config

[Kerbalism.stall.Player.log](https://github.com/Standecco/ROKerbalism/files/3300335/Kerbalism.stall.Player.log)
[OK.Player.log](https://github.com/Standecco/ROKerbalism/files/3300330/OK.Player.log)
[ROv12.7.0_Player.log](https://github.com/Standecco/ROKerbalism/files/3300324/ROv12.7.0_Player.log)

**Comment by Standecco** [comment]
Should be fixed by b21d5b957e9d5c8a15e7d11a0016af4ec9d5a5ff, can you pull the master and confirm that @codebori ?

**Comment by codebori** [comment]
Yes, it works! Thanks!
