### ISSUE TITLE
Infrared Spectrometry 1 should be Biome Specific

### ISSUE THREAD

**Issue by pap1723** [Standecco/ROKerbalism#61]

**Comment by Standecco** [comment]
Infrared spectrometry doesn't seem to exist, perhaps you meant infrared radiometry? If so, ROK doesn't touch the situation/biome mask for RP0infraredRad1, so it depends on RP-1.
For what it's worth, in my configCache it's the same, consistent situation/biome mask = 48 for all the 4 tiers of the experiment. Maybe you meant some other line of instruments?
