### ISSUE TITLE
Sample mass inconsistency.

### ISSUE THREAD

**Issue by UsernamesAreAlwaysTaken** [Standecco/ROKerbalism#7]
https://github.com/Standecco/ROKerbalism/blob/master/GameData/KerbalismConfig/System/Science/CrewScience/Experiments/BasicCapsuleExperiments.cfg

Line 96, you're pulling sample mass from a different experiment.
Minor, but consistency.

**Comment by Gordon-Dry** [comment]
I guess that is the proper fix for
https://github.com/Standecco/ROKerbalism/commit/7e2cbe7c019d4bde2fbf85d69f970ccc157a00c5

**Comment by Standecco** [comment]
that's definitely unintended, thanks for spotting it

**Comment by Standecco** [comment]
Fixed in 45059bb2d2dc1255021cd845a0b4bde11bde4824
