### ISSUE TITLE
v0.9.1: no CO2 scrubbing in Gemini capsule

### ISSUE THREAD

**Issue by willclemmer** [Standecco/ROKerbalism#70]
Gemini capsule in latest release has no CO2 scrubbing (previous issue reported for Mercury capsule was fixed in an inter-release build but Gemini still seems to have the issue)

**Comment by Standecco** [comment]
Are you sure this hasn't been fixed already in master? Have you tried updating your configs?
If you do, just be sure to recover all in-flight manned vessels with shielding before updating, because shielding will get much denser (and effective) and it might wreck your craft's Δv.

**Comment by willclemmer** [comment]
Thanks Standecco for the quick reply!  And thanks for the heads-up on shielding!  :-)

Downloaded latest again this morning (Kerbalism VersionConfig.xml recites this version as 3.9.0), deleted existing folders in GameData and replaced Kerbalism and KerbalismConfig. I confirm I have CO2 scrubbing in Mercury but not Gemini.  Should I be pulling something other than ROKerbalism?

**Comment by pap1723** [comment]
This is due to the updated (and proper) way that the life support modules
are supported. You MUST unlock the life support node on the same level as
Gemini in order to unlock the CO2 scrubber and O2 Pressurization module.

**Comment by willclemmer** [comment]
Thank you pap1723, tested and confirmed.  With "Early Life Support and ISRU" unlocked, the Gemini capsule now has CO2 scrubbing.  This wasn't clear from the tech tree, so if I can offer a suggestion: it might be helpful in a future release to make "Early Life Support and ISRU" a Requirement of "Second Generation Capsules" in the same way that "Crew Survivability" is a requirement of "Basic Capsules".

Thanks folks for the help!  Closing issue.
