### ISSUE TITLE
Update version on CKAN?

### ISSUE THREAD

**Issue by hallgeirl** [Standecco/ROKerbalism#73]
The version of the RO Kerbalism config is a bit outdated on CKAN. The major issue I found that has been fixed in master is this: https://github.com/Standecco/ROKerbalism/issues/72

Any chance of an updated version published to CKAN?

**Comment by Standecco** [comment]
Sorry for the (extremely) late response, I've been very busy in the last couple of weeks. I'm hoping to release asap, now that the latest (possibly save-breaking)  ISRU stuff is in.

**Comment by Standecco** [comment]
Released https://github.com/Standecco/ROKerbalism/releases/tag/v1.0
